# Site Settings
title: My Awesome Site
description: A simple site using the Leap Day theme.
url: https://yourusername.github.io
baseurl: "" # Leave blank if deploying to the root of the repository

# Author Information
author:
  name: Your Name
  email: your-email@example.com

# Theme
remote_theme: pages-themes/leap-day@v0.2.0 # Specifies Leap Day theme and version
plugins:
  - jekyll-remote-theme # Enables remote themes

# Markdown Configuration
markdown: kramdown
kramdown:
  input: GFM # Enables GitHub-flavored Markdown

# Optional: Social Links
social_links:
  twitter: your-twitter-handle
  github: your-github-username
  linkedin: your-linkedin-username

# Permalinks
permalink: /:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: "" # All files
      type: "posts"
    values:
      layout: post

# Build Settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle

# Pagination (optional)
paginate: 5 # Number of posts per page
paginate_path: "/page:num/"

# Analytics (optional)
google_analytics: UA-XXXXXXXXX-X # Replace with your Google Analytics ID
